# Generated by Django 5.0.6 on 2024-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_compra_delete_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='texto_busca',
            field=models.TextField(blank=True, null=True),
        ),
    ]
